apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis
  namespace: monitoring
  labels:
    app: redis
spec:
  namespaceSelector:
    matchNames:
      - shared
  selector:
    matchLabels:
      app: redis
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
