apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: litellm
  namespace: monitoring
  labels:
    app: litellm
spec:
  namespaceSelector:
    matchNames:
      - litellm
  selector:
    matchLabels:
      app: litellm
  endpoints:
    - port: http
      path: /metrics/
      interval: 30s
