apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgres
  namespace: monitoring
  labels:
    app: postgres
spec:
  namespaceSelector:
    matchNames:
      - shared
  selector:
    matchLabels:
      app: postgres
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
