apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflare-tunnel
data:
  config.yaml: |
    tunnel: 8b7166a2-efbf-4c4a-86af-acd6ea54ee44
    credentials-file: /etc/cloudflared/creds/credentials.json
    ingress:
      - hostname: "*.goriok.com"
        service: http://traefik.traefik.svc.cluster.local:80
      - service: http_status:404
