apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: shared
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""             # Sem StorageClass — binding estático
  volumeName: postgres-nvme        # Binding direto ao PV do NVMe
  resources:
    requests:
      storage: 38Gi
