[k3s_server]
oficina-server ansible_host=201.23.81.10

[k3s_agents]
oficina-agent-essential ansible_host=201.23.82.255 k3s_tier=essential k3s_taint=true
oficina-agent-standard  ansible_host=201.23.82.251 k3s_tier=standard  k3s_taint=false

[k3s_cluster:children]
k3s_server
k3s_agents

[k3s_cluster:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new'
