apiVersion: batch/v1
kind: Job
metadata:
  name: taberna-migration
  namespace: taberna
  labels:
    app: taberna
    component: migration
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: taberna
        component: migration
    spec:
      restartPolicy: OnFailure
      imagePullSecrets:
        - name: mgc-registry-credentials
      tolerations:
      - key: tier
        value: standard
        effect: NoSchedule
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: tier
                operator: In
                values:
                - standard
      containers:
        - name: migration
          image: container-registry.br-se1.magalu.cloud/my-registry/taberna:latest
          imagePullPolicy: Always
          command: ["npx", "prisma", "migrate", "deploy"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: taberna-secret
                  key: DATABASE_URL